#!/usr/bin/env php
<?php
require_once __DIR__.'/bootstrap/app.php';

use Cmd\Executor;


$command = $argv[1];
$arguments = array_slice($argv, 2);

try {
    $kernel = new Executor($command, $arguments);
} catch (Throwable $exception) {
    echo $exception->getMessage();
    echo $exception->getTraceAsString();
}





